// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/maintenance-done": {
            "post": {
                "description": "Receives maintenance completion notification from SAP and forwards it to Digital Twin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance Events"
                ],
                "summary": "Handle Maintenance Done Event",
                "parameters": [
                    {
                        "description": "Maintenance Done Event",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MaintenanceDoneEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/maintenance-orders": {
            "post": {
                "description": "Creates a maintenance order in SAP based on equipment information from Digital Twin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance Orders"
                ],
                "summary": "Create Maintenance Order Event",
                "parameters": [
                    {
                        "description": "Maintenance Order Event",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MaintenanceOrderEvent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.MaintenanceOrderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/maintenance-orders/{id}": {
            "get": {
                "description": "Retrieves the current status and details of a maintenance order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Maintenance Orders"
                ],
                "summary": "Get Maintenance Order Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Maintenance Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MaintenanceOrderStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Get service performance metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get Service Metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ComponentStatus": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "goodsMovementType": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "materialUnit": {
                    "type": "string"
                },
                "plant": {
                    "type": "string"
                },
                "requirementQuantity": {
                    "type": "number"
                },
                "storageLocation": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "models.MaintenanceDoneEvent": {
            "type": "object",
            "required": [
                "orderId",
                "status"
            ],
            "properties": {
                "actualWorkHours": {
                    "type": "number"
                },
                "completedAt": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.MaintenanceOperation": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "duration": {
                    "type": "number"
                },
                "durationUnit": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "workCenter": {
                    "type": "string"
                }
            }
        },
        "models.MaintenanceOrderEvent": {
            "type": "object",
            "required": [
                "description",
                "equipmentId",
                "plant"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "equipmentId": {
                    "type": "string"
                },
                "functionalLocation": {
                    "type": "string"
                },
                "maintenanceOrderType": {
                    "type": "string"
                },
                "operations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MaintenanceOperation"
                    }
                },
                "plannedEndTime": {
                    "type": "string"
                },
                "plannedStartTime": {
                    "type": "string"
                },
                "plant": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                }
            }
        },
        "models.MaintenanceOrderResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "maintenanceNotification": {
                    "type": "string"
                },
                "maintenanceOrder": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.MaintenanceOrderStatus": {
            "type": "object",
            "properties": {
                "actualEndTime": {
                    "type": "string"
                },
                "actualStartTime": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "equipment": {
                    "type": "string"
                },
                "maintenanceNotification": {
                    "type": "string"
                },
                "maintenanceOrder": {
                    "type": "string"
                },
                "objectList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ObjectListItemStatus"
                    }
                },
                "operations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OperationStatus"
                    }
                },
                "plant": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.ObjectListItemStatus": {
            "type": "object",
            "properties": {
                "equipment": {
                    "type": "string"
                },
                "functionalLocation": {
                    "type": "string"
                },
                "material": {
                    "type": "string"
                },
                "serialNumber": {
                    "type": "string"
                }
            }
        },
        "models.OperationStatus": {
            "type": "object",
            "properties": {
                "actualWorkQuantity": {
                    "type": "number"
                },
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ComponentStatus"
                    }
                },
                "maintenanceOrderOperation": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "workQuantityUnit": {
                    "type": "string"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SAP Adaptor API",
	Description:      "SAP Adaptor for Maintenance Order Event processing",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
